DROP TABLE IF EXISTS button;
-- DROP TABLE IF EXISTS sqlite_sequence;
CREATE TABLE button (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  position INTEGER NOT NULL,
  action TEXT NOT NULL,
  zone TEXT NOT NULL,
  last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
